name: forrageira
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.20.2

  flutter_native_splash: ^2.4.7
  cupertino_icons: ^1.0.9

  # Firebase
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.2.0
  firebase_storage: ^13.2.0

  # Geolocation
  geolocator: ^14.0.2

  # Image Picker
  image_picker: ^1.1.2

  # State management
  provider: ^6.0.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.8.0
  http: ^1.2.0

  # Notifications & timezone
  timezone: ^0.11.0
  flutter_timezone: ^5.0.2
  flutter_local_notifications: ^21.0.0
  firebase_messaging: ^16.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.4.9
  freezed: ^3.2.5
  json_serializable: ^6.7.1
  fl_chart: ^0.68.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geocoding: ^4.0.0

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo.png
  fullscreen: true

flutter:
  assets:
    - assets/images/grass.jpg

  uses-material-design: true