name: forrageira
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0-180.0.dev

dependencies:

  flutter:
    sdk: flutter

  flutter_native_splash: ^2.4.7
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.0
  cloud_firestore: ^4.17.0
  firebase_storage: ^11.7.0

  #Geolocation
  geolocator: ^11.0.0

  #Supabase
  supabase_flutter: ^2.5.6

  #Image Picker
  image_picker: ^1.1.2

  # State management
  provider: ^6.0.0
  freezed_annotation: ^3.1.0

  # Serialização JSON
  json_annotation:  ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.13.0
  freezed: ^3.2.5
  json_serializable:  ^6.0.0   # Ferramenta de serialização JSON

flutter_native_splash:
  color: "#FFFFFF"
  image:                assets/images  #/logo.png
  fullscreen: true

flutter:

  assets:
    - assets/images/grass.jpg

  uses-material-design: true
