// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHHaMQbuZ6rS9rJXuJCoC3kWsrAAJhlrA',
    appId: '1:1055602958265:web:e0e1413107c1b5f13aa068',
    messagingSenderId: '1055602958265',
    projectId: 'forrageira-963b0',
    authDomain: 'forrageira-963b0.firebaseapp.com',
    storageBucket: 'forrageira-963b0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0FX-HzUKGAjMvVEVL1rCXvcKbsIYvBoo',
    appId: '1:1055602958265:android:c7032ae3fe15fb3b3aa068',
    messagingSenderId: '1055602958265',
    projectId: 'forrageira-963b0',
    storageBucket: 'forrageira-963b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoCTou8vuKGMprmsn80u2krxwbuOKcj4A',
    appId: '1:1055602958265:ios:8227886065ff14f43aa068',
    messagingSenderId: '1055602958265',
    projectId: 'forrageira-963b0',
    storageBucket: 'forrageira-963b0.firebasestorage.app',
    iosBundleId: 'com.example.forrageira',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoCTou8vuKGMprmsn80u2krxwbuOKcj4A',
    appId: '1:1055602958265:ios:8227886065ff14f43aa068',
    messagingSenderId: '1055602958265',
    projectId: 'forrageira-963b0',
    storageBucket: 'forrageira-963b0.firebasestorage.app',
    iosBundleId: 'com.example.forrageira',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHHaMQbuZ6rS9rJXuJCoC3kWsrAAJhlrA',
    appId: '1:1055602958265:web:9c83136778c936583aa068',
    messagingSenderId: '1055602958265',
    projectId: 'forrageira-963b0',
    authDomain: 'forrageira-963b0.firebaseapp.com',
    storageBucket: 'forrageira-963b0.firebasestorage.app',
  );
}
